In [1]:
import numpy as np

1. Сгенерировать матрицу размером 4x9, заполненную случайными целыми из отрезка [0,20] и вывести её на экран.

In [2]:
data = np.random.randint(low=0, high=20+1, size=(4,9))
data

array([[20,  8,  1,  7, 11, 10, 11, 20,  6],
       [17,  6,  2, 15,  4, 15,  7,  4, 15],
       [ 1, 17, 12,  7, 11,  6, 19,  3,  7],
       [ 1, 19, 18,  4,  7,  2, 11, 13,  7]])

2. Вывести на экран элемент с индексами [2,6].

In [3]:
data[2,6]

np.int64(19)

3. Вывести на экран столбец матрицы под номером 3.

In [4]:
data[:,3]

array([ 7, 15,  7,  4])

4. Вывести на экран каждый второй элемент третьей строки матрцы.

In [5]:
data[3,1::2]

array([19,  4,  2, 13])

5. Вывести на экран элементы последнего столбца в обратном порядке.

In [6]:
data[::-1,-1]

array([ 7,  7, 15,  6])

6. Изменить формулу матрицы с 4x9 на 6x6.

In [7]:
data = data.reshape(6, 6)
data

array([[20,  8,  1,  7, 11, 10],
       [11, 20,  6, 17,  6,  2],
       [15,  4, 15,  7,  4, 15],
       [ 1, 17, 12,  7, 11,  6],
       [19,  3,  7,  1, 19, 18],
       [ 4,  7,  2, 11, 13,  7]])

7. Возвести каждый элемент матрицы в заданную степень.

In [8]:
data = data ** 2
data

array([[400,  64,   1,  49, 121, 100],
       [121, 400,  36, 289,  36,   4],
       [225,  16, 225,  49,  16, 225],
       [  1, 289, 144,  49, 121,  36],
       [361,   9,  49,   1, 361, 324],
       [ 16,  49,   4, 121, 169,  49]])

8. Найти минимум на главной диагонали.

In [9]:
data.diagonal().min()

np.int64(49)

9. Найти максимальный элемент в предпоследнем столбце.

In [10]:
data[:,-2].max()

np.int64(361)

10. Определить, образуют ли элементы сжатого до одной оси массива невозрастающую последовательность. Для этого задания обратите внимание на функции diff и all из numpy.

In [11]:
data.reshape(-1)

array([400,  64,   1,  49, 121, 100, 121, 400,  36, 289,  36,   4, 225,
        16, 225,  49,  16, 225,   1, 289, 144,  49, 121,  36, 361,   9,
        49,   1, 361, 324,  16,  49,   4, 121, 169,  49])

In [14]:
np.all(np.vectorize(lambda x: x > 0)(np.diff(data.reshape(-1))))

np.False_

In [15]:
data

array([[400,  64,   1,  49, 121, 100],
       [121, 400,  36, 289,  36,   4],
       [225,  16, 225,  49,  16, 225],
       [  1, 289, 144,  49, 121,  36],
       [361,   9,  49,   1, 361, 324],
       [ 16,  49,   4, 121, 169,  49]])

11. Подсчитать произведение ненулевых элементов побочной диагонали.

In [19]:
np.flip(data, axis=1).diagonal()

array([100,  36,  49, 144,   9,  16])

In [18]:
np.prod(np.flip(data, axis=1).diagonal())

np.int64(3657830400)

12. Создать массив из случайных целых чисел [-20, 20] размерностью 15.

In [20]:
data = np.random.randint(low=-20, high=20 + 1, size=15)
data

array([-19,  -7,  15, -10, -15,  -6,   9, -18,  19,   9, -19,  -3,   4,
        -1,  -2])

13. Выведите только положительные элементы массива.

In [21]:
data[data > 0]

array([15,  9, 19,  9,  4])

14. Посчитайте количество чётных элементов в массиве.

In [22]:
data[data % 2 == 0].shape[0]

5