In [10]:
import numpy as np

# 1. Распаковка данных.

In [226]:
d1 = np.loadtxt(fname='wind-data-1961.csv', comments='%', delimiter=',')
d2 = np.loadtxt(fname='wind-data-1962.csv', comments='%', delimiter=',')
d3 = np.loadtxt(fname='wind-data-1963.csv', comments='%', delimiter=',')
d4 = np.loadtxt(fname='wind-data-1964.csv', comments='%', delimiter=',')
d5 = np.loadtxt(fname='wind-data-1965.csv', comments='%', delimiter=',')
d6 = np.loadtxt(fname='wind-data-1966.csv', comments='%', delimiter=',')
d7 = np.loadtxt(fname='wind-data-1967.csv', comments='%', delimiter=',')
d8 = np.loadtxt(fname='wind-data-1968.csv', comments='%', delimiter=',')
d9 = np.loadtxt(fname='wind-data-1969.csv', comments='%', delimiter=',')
d10 = np.loadtxt(fname='wind-data-1970.csv', comments='%', delimiter=',')

# 2. Заполнить недостающие значения года соответствующим годом. Заполнить недостающие значения скорости ветра в точке средним значением в этой точке.

Функция заполнения столбца года:

In [227]:
def fill_year(data):
    data[:, 0][data[:, 0] == 0] = data[:, 0].max()

Функция заполнения пропусков в реперных точках. (реализована сомнительно):

In [228]:
def fill_wind(data):
    for i in np.arange(data.shape[0]):
        data[i][np.isnan(data[i])] = np.nanmean(data[i])

Проверим:

In [229]:
np.isnan(d1).sum(), d1[:, 0].min()

(np.int64(214), np.float64(0.0))

In [230]:
fill_year(d1)
fill_wind(d1)

In [231]:
np.isnan(d1).sum(), d1[:, 0].min()

(np.int64(0), np.float64(61.0))

# 3. Посчитайте минимальное, максимальное и среднее значение скорости ветра, а также среднее квадратическое отклонение скорости ветра, по всем реперным точкам за все дни (каждое значение считается относительно всего сета). Выведите полученные 4 значения.

Функция подсчёта значений:

In [232]:
def calc_for_all_days(data):
    print('-----------------------------\nyear = {0}'.format(data[0,0]))
    print('min for all = {0}'.format(data[:, 3:].min()))
    print('max for all = {0}'.format(data[:, 3:].max()))
    print('avg for all = {0}'.format(data[:, 3:].mean()))
    print('ms for all = {0}'.format(data[:, 3:].std()))
    print('-----------------------------')

Проверим:

In [233]:
calc_for_all_days(d1)


-----------------------------
year = 61.0
min for all = 0.42
max for all = 33.45
avg for all = 10.531260110893674
ms for all = 5.069212500611363
-----------------------------


# 4. Посчитайте минимальное, максимальное и среднее значение скорости ветра, а также среднее квадратическое отклонение скорости ветра, каждой реперной точки по всем дням. Для каждой точки должен получиться свой набор значений. Выведите полученные значения.

Функция подсчёта значений:

In [234]:
def calc_for_every_point(data):
    return np.column_stack((data[:, 3:].min(axis=0), data[:, 3:].max(axis=0), data[:, 3:].mean(axis=0), data[:, 3:].std(axis=0),))

Проверим:

In [235]:
calc_for_every_point(d1)

array([[ 2.88      , 28.75      , 12.31923288,  5.33093104],
       [ 1.13      , 24.21      , 10.60015861,  4.53943159],
       [ 2.13      , 32.71      , 11.59437268,  4.92760733],
       [ 0.42      , 25.92923077,  7.36138251,  3.91969257],
       [ 2.21      , 28.5       , 11.08645823,  4.56879505],
       [ 0.83      , 25.92923077,  8.0549958 ,  4.12422598],
       [ 1.25      , 25.62      ,  9.96658617,  4.66395322],
       [ 0.58      , 21.37      ,  9.11196955,  4.29765801],
       [ 0.5       , 21.46      ,  8.95826032,  4.01097631],
       [ 1.25      , 26.38      , 10.07196512,  4.22888369],
       [ 2.71      , 29.63      , 13.55899878,  5.50140945],
       [ 2.        , 33.45      , 13.69074069,  5.6887584 ]])

# 5. Посчитайте минимальное, максимальное и среднее значение скорости ветра, а также среднее квадратическое отклонение скорости ветра, всех реперных точек каждого дня. Должен получиться свой набор значений для каждого дня. Добавьте в датасет новую колонку с максимальными значениями по дням. (Подсказка: используйте функции np.hstack и np.reshape). Выведите полученные значения.

Функция для вычисления значений:

In [236]:
def calc_for_every_day(data):
    return np.column_stack((data[:,3:].min(axis=1), data[:,3:].max(axis=1), data[:,3:].mean(axis=1), data[:,3:].std(axis=1)))

Проверим:

In [237]:
calc_for_every_day(d1)

array([[ 9.29      , 18.5       , 13.16071429,  2.60735195],
       [ 6.5       , 17.54      , 11.79833333,  3.28972854],
       [ 6.17      , 18.5       , 11.34166667,  3.50543348],
       ...,
       [ 7.25      , 23.21      , 12.81964286,  4.32031706],
       [ 5.75      , 29.33      , 12.47916667,  6.08288783],
       [ 3.08      , 14.67      ,  6.91166667,  3.32356945]])

Функция, добавляющая новый столбец и вычисляющая максимальные значения по дням для него:

In [238]:
def add_column_and_calc_max(data):
    return np.column_stack((data, data[:, 3:].max(axis=1)))

Проверим:

In [239]:
d1 = add_column_and_calc_max(d1)
d1[0], d1.shape

(array([61.        ,  1.        ,  1.        , 15.04      , 14.96      ,
        13.17      ,  9.29      , 14.72857143,  9.87      , 13.67      ,
        10.25      , 10.83      , 12.58      , 18.5       , 15.04      ,
        18.5       ]),
 (365, 16))

# 6. Для каждого дня найдите точку с наибольшим значением скорости ветра. Выведите массив найденных номеров реперных точек (массив целых чисел).

Функция подсчёта значений:

In [240]:
def calc_max_for_every_day(data):
    return data[:, 3: data.shape[1] - 2].argmax(axis=1) + 1

Проверим:

In [241]:
calc_max_for_every_day(d1)

array([11, 11,  1,  3,  1,  1,  2, 11, 11,  3,  3,  1,  1,  1,  1,  1,  1,
        3,  7,  2,  1,  6,  3,  3, 11,  1, 11, 11, 11, 10,  1,  2,  2,  1,
       11,  1, 11,  1,  1, 11,  1, 11, 11, 11,  3, 11, 11, 11, 11, 11, 11,
       11,  4, 11,  3,  1,  1, 11, 11, 11, 11, 11, 11,  2, 11, 11, 11, 11,
       11, 11,  7, 11, 11, 11, 11, 11, 11,  3,  7,  3, 10, 11, 11, 11,  6,
        6, 11,  2,  1,  2, 11, 11,  3, 11,  3, 11,  3, 10,  6,  5, 10,  3,
        3,  9,  2, 11, 11, 11, 11,  1, 11,  1,  1, 11,  9,  1, 10,  2, 11,
        4, 11,  1, 11,  2, 11, 11, 11, 11, 10,  9, 11,  2,  3,  8,  3,  3,
        3,  3, 11,  8,  3, 11,  7, 11, 11,  3,  1, 11,  3,  1,  3,  1,  6,
       11, 11, 11, 11, 11,  1,  2,  1,  1,  3,  7, 11, 11, 11,  3, 11, 11,
        9, 11,  7, 11, 11, 11,  1, 11, 11, 11, 11,  5,  1, 11,  1,  1,  2,
       11,  5,  5,  5,  2,  1, 11,  1,  1,  1, 10, 11, 11, 11, 11, 11,  3,
       11, 11, 11,  4,  1, 11, 11,  8,  3,  4, 11, 11,  5,  5, 11,  1,  5,
       11,  1, 11,  3,  1

In [242]:
d1[0, 3: d1.shape[1] - 2]

array([15.04      , 14.96      , 13.17      ,  9.29      , 14.72857143,
        9.87      , 13.67      , 10.25      , 10.83      , 12.58      ,
       18.5       ])

# 7. Найдите год, месяц и день, в который была зафиксирована самая большая скорость ветра. Выведите найденную дату.

Функция подсчёта значений:

In [247]:
def calc_max_for_all_days(data):
    return data[data[:, -1].argmax(axis=0), :3]

Проверим:

In [248]:
calc_max_for_all_days(d1)

array([61., 10., 18.])

In [251]:
d1[:, 3:-1].max()

np.float64(33.45)

In [253]:
d1[d1[:, -1].argmax(axis=0), 3:]

array([28.33      , 18.29      , 22.63      , 17.83      , 18.08      ,
       11.96      , 21.84      , 17.33      , 16.17      , 26.38      ,
       22.94928571, 33.45      , 33.45      ])

# 8. Найдите среднюю скорость в январе для каждой реперной точки. Выведите полученные значения.

Функция подсчёта значений:

In [267]:
def calc_for_every_point_in_January(data):
    return data[data[:, 1] == 1][:, 3:-1].mean(axis=0)

Проверим:

In [268]:
calc_for_every_point_in_January(d1)

array([15.2416129 , 12.18279334, 13.55545906,  8.23255051, 11.66711804,
        8.96571429, 11.64966147,  9.20645161,  9.51747253, 10.24531017,
       13.73818859, 14.6318894 ])

In [271]:
d1[d1[:, 1] == 1][:,3].mean()

np.float64(15.241612903225807)

# 9. Сохраните получившийся датасет в csv файл. Проследите, чтобы целые числа были сохранены в целочисленном формате, без нулей в дробной части. Кадое число с плавающей точкой сохраните с точностью ровно в 4 знака после точки.

Функция подготовки и сохранения массива:

In [317]:
def save_data(data, name):

    np.savetxt("./new/{0}.csv".format(name), data, delimiter=",", fmt='%d %d %d %.4f %.4f %.4f %.4f %.4f %.4f %.4f %.4f %.4f %.4f %.4f %.4f %.4f')

Проверим:

In [318]:
save_data(d1, 'd1')

# 10. Посчитайте среднюю скорость ветра для каждого месяца в датасете. выведите полученные значения.

Функция подсчёта значений:

In [273]:
def mean_for_every_month(data):
    return np.array([data[data[:, 1] == 1][:, 3:-1].mean(), 
                     data[data[:, 1] == 2][:, 3:-1].mean(),
                     data[data[:, 1] == 3][:, 3:-1].mean(),
                     data[data[:, 1] == 4][:, 3:-1].mean(),
                     data[data[:, 1] == 5][:, 3:-1].mean(),
                     data[data[:, 1] == 6][:, 3:-1].mean(),
                     data[data[:, 1] == 7][:, 3:-1].mean(),
                     data[data[:, 1] == 8][:, 3:-1].mean(),
                     data[data[:, 1] == 9][:, 3:-1].mean(),
                     data[data[:, 1] == 10][:, 3:-1].mean(),
                     data[data[:, 1] == 11][:, 3:-1].mean(),
                     data[data[:, 1] == 12][:, 3:-1].mean()])

Проверим:

In [274]:
mean_for_every_month(d1)

array([11.56951849, 13.65126284, 11.31739042,  8.66312439,  9.0946947 ,
        9.85003358,  9.2188333 , 10.96371898, 10.28344031, 11.62980998,
        9.23837118, 11.06492113])